[package]
name = "nseventforwarder"
version = "0.1.0"
license = "ISC"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neon = "1"
block2 = "0.5.1"
objc2-app-kit = { version = "0.2.2", features = ["NSEvent", "block2"] }
