[package]
name = "rust-utils"
description = ""
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
exclude = ["index.node"]

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]
path = "rust-utils-rs/lib.rs"

[dependencies]
neon = "1"
lnk_parser = "0.4.1"
